introduce e2e tests into pre-push script to avoid breaking the build

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,4 +7,9 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+npm run test:e2e:prod || {
+  echo "❌ End-to-end tests failed! Fix the issues before pushing."
+  exit 1
+}
+
 echo "✅ Build successful! Proceeding with push..."
